# Generated by Django 3.1.5 on 2021-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210117_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='hello', help_text='The unique slug to the note', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
