# Generated by Django 3.1.5 on 2021-01-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Whether the file will be visible to other people'),
        ),
    ]
