# Generated by Django 3.1.5 on 2021-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20210126_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(default='hello', help_text='A brief description of the note that will be displayed in the note preview.', max_length=200),
            preserve_default=False,
        ),
    ]
