# Generated by Django 3.1.5 on 2021-02-01 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0009_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, help_text='Use this to remove unwanted comments via admin page'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(help_text='The note this comment is made on on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Specify the parent if this comment is made as a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote this comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
